fields:
  - name: tag
    type: dockertags
    caption: Version
    tooltip: Version of Windmill to install
    required: true
    image: ghcr.io/windmill-labs/windmill

  - name: deploymentType
    type: list
    caption: Deployment Type
    tooltip: Development is for a single node setup and production are for multi-node setups
    values:
      - value: development
        caption: Development
      - value: production
        caption: Production
    default: development

  - name: dbDiskLimit
    type: spinner
    caption: Database Disk Size
    tooltip: Size of the database disk in GB
    default: 100
    required: true
    editable: true
    min: 1

  - name: storageDiskLimit
    type: spinner
    caption: Storage Disk Size
    tooltip: Size of the storage disk in GB
    default: 100
    required: true
    editable: true
    min: 1

  - name: workerDefault
    type: spinner
    caption: Default Worker
    tooltip: The default worker group is the one that will execute jobs with any tags except the native ones.
    default: 1
    required: true
    editable: true
    min: 1

  - name: workerNative
    type: spinner
    caption: Native Worker
    tooltip: The native worker group is the one that will execute jobs with the native tags.
    default: 1
    required: true
    editable: true
    min: 1

  - name: workerReport
    type: spinner
    caption: Report Worker
    tooltip: The report worker group is the one that will execute jobs with the report tags.
    default: 1
    required: true
    editable: true
    min: 1

  - name: lspEnabled
    type: checkbox
    caption: Enable LSP
    tooltip: Enable Language Server Protocol for code completion.
    default: true
